name: qr_code_utils_android
description: Android implementation of the qr_code_utils plugin.
repository: https://github.com/atech-dev/qr_code_utils/tree/main/qr_code_utils_android
issue_tracker: https://github.com/atech-dev/qr_code_utils/issues?q=is%3Aissue+is%3Aopen
homepage: https://atech.co.ao/
version: 0.0.3

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

flutter:
  plugin:
    implements: qr_code_utils
    platforms:
      android:
        package: dev.atech.qr_code_utils
        pluginClass: QrCodeUtilsPlugin

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
